[package]
name = "tcpserver"
version = "0.1.0"
edition = "2021"

[dependencies]
tcp = {path = "../tcp"}
tokio = { version = "1.37.0", features = ["full"] }
mongodb = "2.8.2"
serde = { version = "1.0", features = ["derive"] }